[package]
name = "day10"
version = "0.1.0"
authors = ["Mario Juarez <mario@mjp.one>"]
edition = "2018"

[dependencies]
helpers = { path = "../helpers" }
phf = { version = "0.10.0", features = ["macros"] }